version: '3'
services:
  tomcat:
    image: 'tomcat:8.5.37-jre8-alpine'
    container_name: 'tomcat-8'
    ports:
      - '8080:8080'
    volumes:
      - ./tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./tomcat/conf/server.xml:/usr/local/tomcat/conf/server.xml
      - ./build/libs/firstapp.war:/usr/local/tomcat/webapps/firstapp.war
      - ./tomcat/logs:/usr/local/tomcat/logs
      - ./tomcat/conf/manager.xml:/usr/local/tomcat/conf/Catalina/localhost/manager.xml
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=okocim
      - POSTGRES_USER=sunday
    volumes:
      - ./db_data/data:/var/lib/postgresql/data
      - ./db_data/init/init.sql:/docker-entrypoint-initdb.d/init.sql
